import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Sorgonte</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="/leaflet.css"></link>
        <script src="/leaflet.js"></script>
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Sorgonte
        </h1>

        <p className={styles.description}>
          Página de inicio - Proyecto 1 IC8017
        </p>

        <div id="map" style={{width: 750, height: 550}}></div>

        <script src="/index1.js"></script>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
